version: '3.3'
services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4566:4566" # port of to where localstack can be addressed to Edge port
    environment:
      - SERVICES=dynamodb
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=4566
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=${DOCKER_LOCATION}
      - AWS_ACCESS_KEY_ID=teste
      - AWS_SECRET_ACCESS_KEY=teste
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_OUTPUT=json
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "./notification.json:/opt/code/localstack/notification.json"
      - "./init-aws.sh:/docker-entrypoint-initaws.d/init-aws.sh"